services:
  siszarponthedisco:
    container_name: siszarp
    env_file: .env
    image: dzioczek/siszarponthedisco:latest
    build:
      context: .
      dockerfile: SiszarpOnTheDisco/Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - "/home/mis/signal-cli:/signal/config"
