services:
  signalapi:
    container_name: signalApi
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=json-rpc
      - SIGNAL_CLI_CONFIG_DIR=/home/.local/share/signal-cli/
    ports:
      - "8999:8080"
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://signalapi:8999/v1/health"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
  siszarponthedisco:
    container_name: siszarp
    env_file: .env
    environment:
      - SIGNAL_API_ADDRESS=signalapi:8999
    image: dzioczek/siszarponthedisco:latest
    build:
      context: .
      dockerfile: SiszarpOnTheDisco/Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      signalapi:
        condition: service_healthy
        restart: true
